FROM node:22-bookworm-slim

WORKDIR /app
COPY package*.json ./
COPY apps ./apps
COPY packages ./packages
COPY configs ./configs
COPY scripts ./scripts
COPY tailwind.config.ts tsconfig.json ./
RUN npm ci
RUN npm run build:web

EXPOSE 3000
CMD ["npm", "run", "start:web"]
