FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends python3 curl ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
COPY apps ./apps
COPY packages ./packages
COPY configs ./configs
COPY scripts ./scripts
COPY tsconfig.json ./
RUN npm ci

CMD ["npm", "run", "dev:worker"]
